'use strict';
// Chromium tests use a fake preload, an isolated profile, and blocked network.
const { app, BrowserWindow, session } = require('electron');
const fs = require('node:fs');
const path = require('node:path');
const out = path.resolve(__dirname, '../../voice-content-tests');
app.setPath('userData', path.join(out, 'profile'));
const timeout = setTimeout(() => app.exit(2), 30000);
app.whenReady().then(async () => {
  fs.mkdirSync(out, { recursive: true });
  const blockedRequests = [];
  session.defaultSession.webRequest.onBeforeRequest((details, callback) => {
    const blocked = !/^(file:|data:|devtools:)/.test(details.url);
    if (blocked) blockedRequests.push(details.url);
    callback({ cancel: blocked });
  });
  const win = new BrowserWindow({ width: 740, height: 660, frame: false, transparent: true, backgroundColor: '#00000000', resizable: true, show: false,
    webPreferences: { preload: path.join(__dirname, 'preload.cjs'), sandbox: true, contextIsolation: true, nodeIntegration: false, backgroundThrottling: false } });
  win.setContentProtection(true);
  await win.loadFile(path.resolve(__dirname, '../content.html'));
  win.showInactive();
  const checks = await win.webContents.executeJavaScript(`(async () => {
    const checks = [], el = id => document.getElementById(id);
    const check = (name, passed) => { checks.push({name,passed:!!passed}); if (!passed) throw new Error(name); };
    const tick = () => new Promise(resolve => requestAnimationFrame(() => setTimeout(resolve, 15)));
    const draft = value => { el('manualQuestion').value = value; el('manualQuestion').dispatchEvent(new Event('input')); };
    contentTest.emit({type:'answer-delta',id:40,text:'OLD duplicate',seq:4});
    contentTest.emit({type:'answer-delta',id:40,text:'New buffered text.',seq:6});
    contentTest.resolveSnapshot({seq:5,live:true,startedAt:Date.now(),question:'Snapshot question',answer:{id:40,question:'Snapshot question',text:'Initial snapshot. ',state:'generating'},sources:{remote:'listening'}});
    for (let i=0;i<30 && el('answerBody').textContent!=='Initial snapshot. New buffered text.';i++) await tick();
    check('Snapshot replays only newer events without lost or duplicate text', el('answerBody').textContent==='Initial snapshot. New buffered text.');
    contentTest.emit({type:'answer-delta',id:40,text:'DUPLICATE',seq:6}); await tick();
    check('Repeated event sequence is ignored', !el('answerBody').textContent.includes('DUPLICATE'));
    check('Question and answer use readable default sizes', getComputedStyle(el('currentQuestion')).fontSize==='17px' && getComputedStyle(el('answerBody')).fontSize==='20px');
    check('Composer stays hidden by default', el('composer').classList.contains('hidden'));
    check('Default popup has no brand, transcript, or footer', !document.querySelector('footer,.brand,#transcript'));
    check('Expanded popup reserves at least 500px for answer reading', el('answerScroll').clientHeight>=500);
    check('Expanded popup gives answer at least 74 percent of height', el('answerScroll').clientHeight/innerHeight>=.74);
    contentTest.emit({type:'answer-done',id:40});
    contentTest.emit({type:'settings-changed',settings:{voiceFallbackEnabled:true}});
    contentTest.emit({type:'voice-command-status',status:'queued',message:'Waiting for the current answer. <img src=x>'});
    check('Voice-command status is visible and rendered as text',!el('voiceCommandStatus').classList.contains('hidden')&&el('voiceCommandStatus').textContent.includes('Waiting')&&!el('voiceCommandStatus').querySelector('img'));
    contentTest.emit({type:'settings-changed',settings:{voiceFallbackEnabled:false}});
    check('Disabled voice fallback uses no popup reading space',el('voiceCommandStatus').classList.contains('hidden'));
    contentTest.emit({type:'question',text:'A follow-up heard after this answer'});
    contentTest.emit({type:'question-preview',text:'Another question is forming',pending:true});
    check('Incoming question never relabels a completed answer', el('currentQuestion').textContent==='Snapshot question');
    contentTest.emit({type:'answer-start',id:41,question:'Explain closures.'});
    contentTest.emit({type:'answer-delta',id:41,text:'A closure remembers its lexical scope.\\n\\n- Scope: Variables from the enclosing function.\\n- State: Independent state per closure.\\n\\n<script>window.__unsafe=true</script><img src=x onerror=window.__unsafe=true>\\n\\n' + Array.from({length:30},(_,i)=>'Paragraph '+i+' remains readable while the answer streams.').join('\\n\\n')});
    await tick();
    check('Model HTML is displayed as text, never executed', !window.__unsafe && !el('answerBody').querySelector('script,img,iframe') && el('answerBody').textContent.includes('<script>'));
    check('Bullet labels are emphasized and lead answer has reading hierarchy', el('answerBody').querySelector('li strong')?.textContent==='Scope:' && el('answerBody').querySelector('p.lead'));
    check('Streaming begins at first sentence', el('answerScroll').scrollTop===0);
    contentTest.emit({type:'answer-delta',id:41,text:'\\n\\nMore incoming text.'}); await tick();
    check('Streaming never automatically jumps from first sentence', el('answerScroll').scrollTop===0);
    el('answerScroll').scrollTop=240;
    contentTest.emit({type:'answer-delta',id:41,text:'\\n\\nAnother incoming paragraph.'}); await tick();
    check('Streaming preserves the readers existing scroll position', Math.abs(el('answerScroll').scrollTop-240)<2);
    contentTest.emit({type:'answer-start',id:42,question:'A new question'});
    contentTest.emit({type:'answer-delta',id:42,text:'A new answer starts here.'}); await tick();
    check('Only a new answer resets scrolling to the top', el('answerScroll').scrollTop===0);
    contentTest.emit({type:'answer-delta',id:41,text:'STALE generation'}); await tick();
    check('Late tokens from an old answer are ignored', !el('answerBody').textContent.includes('STALE'));
    contentTest.emit({type:'answer-error',id:42,message:'Provider quota reached.'}); await tick();
    check('Provider error is visible while partial answer remains readable', el('message').textContent==='Provider quota reached.' && el('answerBody').textContent==='A new answer starts here.');
    el('composeButton').click(); draft('Explain closures'); contentTest.rejectNext(); el('askButton').click(); await tick();
    check('Manual input is optional and failed submission preserves draft', !el('composer').classList.contains('hidden') && el('manualQuestion').value==='Explain closures' && contentTest.calls().asks.length===1 && el('message').textContent.includes('not connected'));
    // A new accepted answer clears the error from the previous answer.
    el('askButton').click(); el('askButton').click();
    check('Manual ask immediately blocks duplicate submissions', contentTest.calls().asks.length===2 && el('askButton').disabled);
    contentTest.emit({type:'answer-start',id:43,question:'Explain closures',automatic:false}); await tick();
    check('Accepted manual question clears and closes its optional input', el('manualQuestion').value==='' && el('composer').classList.contains('hidden'));
    contentTest.emit({type:'answer-delta',id:43,text:'A clear answer.'});
    contentTest.finish({type:'answer-done',id:43}); await tick();
    el('composeButton').click(); draft('First draft'); el('askButton').click(); draft('Next draft before acknowledgement');
    contentTest.emit({type:'answer-start',id:44,question:'First draft',automatic:false}); await tick();
    check('Accepted acknowledgement cannot erase a newer typed draft', el('manualQuestion').value==='Next draft before acknowledgement' && !el('composer').classList.contains('hidden'));
    el('cancelAnswer').click(); await tick();
    check('Stop answer is reachable without opening setup', contentTest.calls().cancel===1 && el('cancelAnswer').classList.contains('hidden'));
    el('dismissComposer').click(); el('menuButton').click(); el('largerText').click(); await tick();
    check('Text size changes save through the shared preference', contentTest.calls().fonts.at(-1)===21 && getComputedStyle(el('answerBody')).fontSize==='21px');
    el('backgroundOpacity').value='70'; el('backgroundOpacity').dispatchEvent(new Event('input')); el('backgroundOpacity').dispatchEvent(new Event('change')); await tick();
    check('Translucent background adjustment keeps answer text fully opaque', contentTest.calls().opacity.at(-1)===70 && getComputedStyle(el('answerBody')).opacity==='1' && getComputedStyle(document.querySelector('.surface')).backgroundColor.endsWith('0.7)'));
    el('openSetup').click(); await tick();
    check('Opening configuration does not stop audio', contentTest.calls().setup===1 && contentTest.calls().stops===0);
    el('closeContent').click(); await tick();
    check('Close uses dedicated stop-and-return-to-configuration action', contentTest.calls().close===1);
    contentTest.emit({type:'session-stopped',reason:'Listening stopped.'}); await tick();
    check('Stopped listening is visible in the compact strip', el('statusText').textContent==='Stopped');
    contentTest.emit({type:'session-reset'}); await tick();
    check('Session reset removes stale question and answer', el('currentQuestion').textContent==='' && el('answerBody').textContent==='' && !el('emptyState').classList.contains('hidden'));
    const requestsBeforeExample=contentTest.calls().asks.length;
    el('emptyExample').click();await tick();
    check('User can open an explicitly offline example without an AI request',el('answerBody').textContent.includes('lexical environment') && el('statusText').textContent==='Example · Offline' && contentTest.calls().asks.length===requestsBeforeExample);
    contentTest.emit({type:'session-reset'});contentTest.emit({type:'session-started'});await tick();
    check('Offline example cannot replace an active listening session',el('emptyExample').disabled && el('showExample').disabled);
    contentTest.emit({type:'session-stopped',reason:'Listening stopped.'});
    contentTest.emit({type:'session-reset'});draft('');
    contentTest.emit({type:'hotkey-answer'});await tick();
    check('Answer shortcut consults the authoritative pending question without repeating an old answer',contentTest.calls().pending.length===1&&contentTest.calls().pending[0].trigger==='hotkey'&&contentTest.calls().asks.length===requestsBeforeExample&&el('message').textContent.includes('No recent unanswered'));
    el('dismissComposer').click();contentTest.emit({type:'question',text:'Latest complete question'});
    contentTest.emit({type:'hotkey-answer'});contentTest.emit({type:'hotkey-answer'});
    check('Answer shortcut delegates pending submission once and blocks duplicates',contentTest.calls().pending.length===2&&contentTest.calls().asks.length===requestsBeforeExample);
    contentTest.emit({type:'answer-start',id:70,question:'Latest complete question',automatic:false});
    contentTest.emit({type:'question',text:'Next pending question while the first answer streams'});
    contentTest.emit({type:'hotkey-answer'});
    check('Answer shortcut queues through main while preserving the generating answer',contentTest.calls().pending.length===3&&contentTest.calls().cancel===1&&el('currentQuestion').textContent==='Latest complete question'&&el('answerScroll').getAttribute('aria-busy')==='true');
    contentTest.finish({type:'answer-done',id:70});await tick();
    el('composeButton').click();draft('Typed question stays manual');contentTest.emit({type:'hotkey-answer'});await tick();
    check('Answer shortcut never sends a typed draft implicitly',contentTest.calls().pending.length===4&&contentTest.calls().asks.length===requestsBeforeExample&&el('manualQuestion').value==='Typed question stays manual');
    el('askButton').click();contentTest.emit({type:'answer-start',id:71,question:'Typed question stays manual',automatic:false});await tick();
    check('Typed Ask remains manual and clears only after acceptance',contentTest.calls().asks.at(-1).question==='Typed question stays manual'&&el('manualQuestion').value===''&&el('composer').classList.contains('hidden'));
    contentTest.finish({type:'answer-done',id:71});await tick();
    contentTest.emit({type:'session-reset'});contentTest.emit({type:'answer-start',id:72,question:'Previously answered question'});contentTest.emit({type:'answer-done',id:72});contentTest.emit({type:'hotkey-answer'});
    await tick();check('Answer shortcut cannot silently reuse a previously answered question',contentTest.calls().pending.length===5&&contentTest.calls().asks.at(-1).question==='Typed question stays manual'&&el('message').textContent.includes('No recent unanswered'));
    const grip=el('resizeHandle'),baseWidth=innerWidth,baseHeight=innerHeight;
    grip.focus();for(const key of ['ArrowRight','ArrowRight','ArrowDown'])grip.dispatchEvent(new KeyboardEvent('keydown',{key,bubbles:true}));await tick();
    check('Accessible resize grip coalesces keyboard increments through IPC',contentTest.calls().resizes.length===1 && contentTest.calls().resizes[0].width===baseWidth+40 && contentTest.calls().resizes[0].height===baseHeight+20);
    const pointer=(type,x,y,id=1)=>grip.dispatchEvent(new PointerEvent(type,{pointerId:id,button:0,screenX:x,screenY:y,bubbles:true}));
    contentTest.holdResize(true);pointer('pointerdown',100,100);pointer('pointermove',120,110);pointer('pointermove',140,130);await tick();
    check('Pointer resizing uses screen deltas and coalesces before paint',contentTest.calls().resizes.length===2 && contentTest.calls().resizes[1].width===baseWidth+40 && contentTest.calls().resizes[1].height===baseHeight+30);
    pointer('pointermove',900,900,2);pointer('pointermove',160,150);await tick();
    check('Resize requests remain serial while preserving the newest pointer position',contentTest.calls().resizes.length===2);
    contentTest.finishResize();await tick();await tick();
    check('Latest resize is dispatched after the previous request settles',contentTest.calls().resizes.length===3 && contentTest.calls().resizes[2].width===baseWidth+60 && contentTest.calls().resizes[2].height===baseHeight+50);
    pointer('pointerup',160,150);pointer('pointermove',300,300);contentTest.finishResize();contentTest.holdResize(false);await tick();
    check('Releasing the resize handle ends the drag',contentTest.calls().resizes.length===3);
    contentTest.emit({type:'session-started'});
    contentTest.emit({type:'answer-start',id:80,question:'Earlier answered question'});
    contentTest.emit({type:'answer-delta',id:80,text:'Earlier answer stays paired with its own question.'});
    contentTest.emit({type:'answer-done',id:80});
    contentTest.emit({type:'question-status',status:'held',reason:'statement',message:'Captured speech; the question end is uncertain.',text:'A bounded buffer using multiple producers. <img src=x>',canSubmit:true,questionId:'q-next',revision:1});await tick();
    check('Held question stays visible with a recovery action without relabeling the previous answer',!el('questionRecovery').classList.contains('hidden')&&el('questionRecoveryText').textContent.includes('bounded buffer')&&!el('questionRecoveryText').querySelector('img')&&el('statusText').textContent==='Question held · Listening'&&el('currentQuestion').textContent==='Earlier answered question'&&!el('answerCaptured').disabled);
    const pendingBeforeRecovery=contentTest.calls().pending.length;el('answerCaptured').click();await tick();
    check('Visible recovery uses the shared pending submission path',contentTest.calls().pending.length===pendingBeforeRecovery+1);
    contentTest.emit({type:'question-status',status:'blocked',reason:'incomplete-audio',message:'Some speech was not finalized. Please repeat the full question.',text:'Unfinished constraint',canSubmit:false});await tick();
    check('Missing final audio explains the blocker and never offers partial submission',el('statusText').textContent==='Question needs attention'&&el('questionRecoveryMessage').textContent.includes('repeat the full question')&&el('answerCaptured').disabled&&el('answerCaptured').classList.contains('hidden'));
    contentTest.emit({type:'question-preview',text:'What is binary search?',pending:true});await tick();
    check('New question speech clears the older held state',el('questionRecovery').classList.contains('hidden')&&el('statusText').textContent==='Finishing question');
    contentTest.emit({type:'session-stopped',reason:'Listening stopped.'});await tick();
    check('Stopped sessions clear recovery controls',el('questionRecovery').classList.contains('hidden'));
    check('Popup contains no native title tooltips', !document.querySelector('[title]'));
    contentTest.emit({type:'settings-changed',settings:{answerFontSize:20,backgroundOpacity:92}});
    return checks;
  })()`);
  const smoke = await win.webContents.executeJavaScript('window.runContentSmokeTest()');
  if (!smoke.ok) throw new Error('Content smoke failed');
  fs.writeFileSync(path.join(out, 'content-large.png'), (await win.webContents.capturePage()).toPNG());
  win.setSize(560, 480);
  await new Promise(resolve => setTimeout(resolve, 150));
  const small = await win.webContents.executeJavaScript(`(async()=>{
    const checks=[],check=(name,passed)=>{checks.push({name,passed:!!passed});if(!passed)throw new Error(name)};
    const el=id=>document.getElementById(id),tick=()=>new Promise(resolve=>requestAnimationFrame(()=>setTimeout(resolve,15)));
    check('Small popup keeps at least 345px of answer reading height',el('answerScroll').clientHeight>=345);
    check('Small popup keeps answer text at20px',getComputedStyle(el('answerBody')).fontSize==='20px');
    check('Small popup has no horizontal page overflow',document.documentElement.scrollWidth===innerWidth && el('answerScroll').scrollWidth===el('answerScroll').clientWidth);
    contentTest.emit({type:'answer-start',id:90,question:'A very long question about '+('shared services and constraints '.repeat(18))});
    contentTest.emit({type:'answer-delta',id:90,text:'A readable first sentence.\\n\\n'+String.fromCharCode(96).repeat(3)+'js\\nconst veryLongIdentifier = '+JSON.stringify('x'.repeat(190))+';\\n'+String.fromCharCode(96).repeat(3)});await tick();
    check('Long questions collapse to three lines with an expansion control',!el('expandQuestion').classList.contains('hidden') && el('currentQuestion').clientHeight<75);
    el('expandQuestion').click();await tick();check('Question expands only on request',el('currentQuestion').classList.contains('expanded'));
    el('expandQuestion').click();await tick();
    const code=el('answerBody').querySelector('pre');
    check('Long code scrolls within its code block without widening the popup',code.scrollWidth>code.clientWidth && el('answerScroll').scrollWidth===el('answerScroll').clientWidth);
    return checks;
  })()`);
  await win.webContents.executeJavaScript('window.runContentSmokeTest()');
  fs.writeFileSync(path.join(out, 'content-small.png'), (await win.webContents.capturePage()).toPNG());
  const hydrationWindow = new BrowserWindow({ width: 740, height: 660, show: false,
    webPreferences: { preload: path.join(__dirname, 'preload.cjs'), sandbox: true, contextIsolation: true, nodeIntegration: false, backgroundThrottling: false } });
  await hydrationWindow.loadFile(path.resolve(__dirname, '../content.html'));
  const hydration = await hydrationWindow.webContents.executeJavaScript(`(async()=>{
    const tick=()=>new Promise(resolve=>setTimeout(resolve,30));
    contentTest.emit({type:'hotkey-answer',seq:2});
    contentTest.resolveSnapshot({seq:3,live:false,answer:{id:null,question:'',text:'',state:'idle'},sources:{}});
    await tick();contentTest.emit({type:'hotkey-answer',seq:2});await tick();
    const passed=contentTest.calls().pending.length===1&&contentTest.calls().asks.length===0;
    if(!passed)throw new Error('Snapshot dropped or duplicated buffered shortcut');
    return {name:'A shortcut buffered before snapshot hydration runs once even below snapshot sequence',passed};
  })()`);
  hydrationWindow.destroy();
  fs.writeFileSync(path.join(out, 'results.json'), JSON.stringify({ ok: true, count: checks.length + small.length + 1, checks: [...checks, ...small, hydration], smoke, blockedRequests }, null, 2));
  clearTimeout(timeout); app.exit(0);
}).catch(error => { fs.mkdirSync(out, { recursive: true }); fs.writeFileSync(path.join(out, 'error.txt'), error.stack); clearTimeout(timeout); app.exit(1); });
